[package]
name = "hdfc-cc-parser-rs"
version = "0.1.0"
authors = ["Joe Paul <joeirimpan@gmail.com>"]
repository = "https://github.com/joeirimpan/hdfc-cc-parser-rs"
keywords = ["HDFC", "credit card", "bill"]
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
chrono = "0.4.23"
csv = "1.1.6"
pdf = { git = "https://github.com/pdf-rs/pdf", features = [ "euclid" ] }
pdf_tools = { git = "https://github.com/pdf-rs/pdf_tools"}
regex = "1.7.1"
